apiVersion: v1
kind: Service
metadata:
  name: {{ include "vectis-server.fullname" . }}
  labels:
    {{- include "vectis-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.pesitPort }}
      targetPort: pesit
      protocol: TCP
      name: pesit
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vectis-server.selectorLabels" . | nindent 4 }}
